#ifndef RESOURCE_H
#define RESOURCE_H
#include <windef.h>
#include <QGridLayout>
#include <QGroupBox>
#include <QWidget>
#include <QDebug>
#include <sqlext.h>
#include <QStyleFactory>
#include <QStandardItem>
#include <QStandardItemModel>
#include <QTableView>
#include <QAbstractItemModel>
#include <QAbstractItemDelegate>
#include <QAbstractItemView>
#include <QtSql/QSqlDatabase>
#include <QtSql/QSqlQuery>
#include <QSqlQueryModel>
#include <QSqlTableModel>
#include <QSettings>
#include <QMessageBox>
#include <QtSql/QSqlError.h>
#include <QEvent>
#include <QKeyEvent>
#include <QSqlRecord>
#include <map>
#endif // RESOURCE_H
